// =====================================================================
// ÖSS (Özel Sağlık Sigortası) - Aksigorta "Aksağlık Sigortası" Özel
// Şartları Soru-Cevap Motoru
// ---------------------------------------------------------------------
// 30.07.2026 eklendi: tssOzelSartSSS.js ile AYNI desen/mimari, ama FARKLI
// bir belgeye dayanıyor. Kullanıcı, TSS için kullanılan Aksigorta TSS
// belgesiyle bu belgenin (Aksigorta "Aksağlık Sigortası" - yani Özel
// Sağlık Sigortası/ÖSS Özel Şartları) FARKLI ürünler/belgeler olduğunu
// doğruladı ("Ayrı belge, ayrı cevap" tercihi) - bu yüzden ÖSS ve TSS
// artık conversationEngine.js'de BAĞIMSIZ birer soru-cevap modülü olarak
// çalışıyor (bkz. BILGI_SORU_MODULLERI eşlemesi).
//
// NOT: Kullanıcı ayrıca "Doğum Sigortası" adında, hem ÖSS'ye hem TSS'ye
// eklenebilen bir PAKET/ek teminat belgesi de paylaştı (Acıbadem'in
// "Kişiye Özel Doğum Sağlık Sigortası Özel Şartları") - ancak kullanıcının
// kendi ifadesiyle "bu paketi de daha sonra ürünlere ekleyeceğiz" (yani
// şimdilik entegre EDİLMEYECEK). Bu yüzden bu dosyada/akışta doğum
// sigortası paketiyle ilgili HİÇBİR şey yok - ileride ayrı bir talep
// geldiğinde eklenecek.
// =====================================================================

const { mesajGonder } = require("./anthropicMesaj");

const OZEL_SART_METNI = `
AKSAĞLIK SİGORTASI (ÖZEL SAĞLIK SİGORTASI - ÖSS) ÖZEL ŞARTLARI

1. SİGORTANIN KONUSU VE KAPSAMI
Sağlık sigortaları, sigortalının sigorta süresi içerisinde kaza ve/veya hastalık halinin gerektirdiği tedavi giderlerini, sağlık sigortası genel ve özel şartları ile poliçe ekinde verilen teminat tablosu doğrultusunda güvence altına almaktadır.
Sigorta Sözleşmesi; Sigorta Ettiren'in ve Sigortalı'nın Sağlık Beyan ve Başvuru Formu, Tanımlar, Sağlık Sigortası Genel ve Özel Şartları, Genel ve Özel İstisnalar, Poliçe ve eklerinden oluşan, Sigortacı ve Sigorta Ettiren arasındaki anlaşmadır.
Sigorta Sözleşmesinin geçerli olduğu süre içerisinde kanun, yönetmelik ve tüzüklerle yapılanlar dışında tüm değişiklikler ve ilaveler, yazılı olarak talep edilmesi ve karşılıklı olarak mutabık kalınması halinde geçerlidir. Sigorta Sözleşmesi bir (1) yıl için akdedilir. Yenilemeler sırasında Sigortacı'nın özel şartlarda, teminatlarda, prim tutarlarında ve ödeme şekillerinde değişiklik yapma hakkı saklıdır.
Poliçe kapsamında yer alan teminatlar, sadece poliçede Sigortalı olarak belirtilen kişiler için ayrı ayrı geçerli olup, poliçede Sigortalı olarak yer almayan kişiler sigorta teminat kapsamından yararlanamazlar.

2. TANIMLAR
Acil Durum: Poliçe genel ve özel şartları gereği Teminat Dışı Kalan Haller ile Bekleme Süreli durumlar arasında yer almayan, ani bir hastalık veya bedensel yaralanma sonucunda ortaya çıkan ve geciktirilmesi mümkün olmayacak tıbbi veya cerrahi bakım gerektiren, hastaneye yatırılsın veya yatırılmasın, aşağıdaki Acil Durum listesinde belirtilen rahatsızlıklar için, bir hastanenin acil servisinde hizmet almayı gerektiren sağlık durumudur. Dünya Sağlık Örgütü tarafından tanımlanan Acil Durumlar arasında (kısaca): trafik kazası, akut miyokard enfarktüsü (kalp krizi), apandisit, menenjit, ani felçler, suda boğulma, yüksekten düşme, ciddi iş kazası, uzuv kopmaları, elektrik çarpması, donma, soğuk çarpması, ısı çarpması, tahriş edici gazların teneffüsü, darbe sonucu sinir kopması, yılan/akrep/örümcek sokması sonucu ciddi alerjik tablolar, hayvan ısırıkları (ciddi cerrahi müdahale gerektiren), her türlü 2. ve 3. derece yanıklar, hayati tehlike arz eden zehirlenmeler, tüm kırık ve çıkıklar, akut solunum problemleri, travma/kaza sonucu şuur kaybı, mide perforasyonu, iç organ zedelenmesi, ensefalit, beyin apsesi, dekompresyon (dalgıç) hastalığı, travma sonucu masif kanamalar, kurşunlanma/bıçaklanma/kavga (cürüm işlemek hariç), epilepsi krizi, gebelik zehirlenmesi, travmaya bağlı sütür gerektiren cilt kesikleri, hipertansiyon krizleri, yüksek ateş (39,5 ve üzeri), diyabetik ve üremik koma, renal kolik, ciddi genel durum bozukluğu sayılmaktadır.
Anlaşmalı Kuruluş: Sigortacı ile Sağlık Kurumu arasında yapılan anlaşmalı kurum sözleşmesi kapsamında ve Sigortacı tarafından sigorta sözleşmesi ve/veya ilgili teminat için geçerli olduğu belirtilmiş olan Sigortalının teminat kapsamında ve limit dahilindeki tedavi giderlerini doğrudan sigortacıdan almayı kabul eden hekimler, hastaneler, klinikler, tıp merkezleri, eczaneler, doktorlar, laboratuvarlar ve fizik tedavi merkezleridir.
Anlaşmalı Olmayan Kuruluş ve Doktorlar: Sigortalının teminat kapsamındaki tedavi giderlerinin doğrudan sigortacıdan alınması ile ilgili özel bir sözleşmesi olmayan, Sigortacı ile Sağlık Kurumu arasındaki anlaşmalı kurum sözleşme şartlarını kabul etmeyen ve kendi faturasını düzenleyen doktorlar, hastaneler, klinikler, tıp merkezleri, eczaneler, laboratuvarlar, fizik tedavi merkezleri vb.dir.
Anlaşmalı Sağlık Kurumları Ağı/Network: Sigortalı tarafından tercih edilen poliçede Sigortacının yer verilmesine uygun gördüğü anlaşmalı sağlık kurumlarını ifade eder. Güncel listeye www.aksigorta.com.tr adresinden ulaşılabilir; Sigortacı, sigorta süresi içinde önceden bildirimde bulunmaksızın networkte değişiklik yapabilir. Liste bilgilendirme amaçlıdır, hizmet alınmadan önce mutlaka Sigortacı'dan provizyon alınması gerekmektedir.
Bekleme Süresi: Sigortalı'nın ilk sigortalanma tarihi ile başlayan ve bu sigorta sözleşmesinin Bekleme Süreleri kısmında belirtilen ve varsa Sigortacı'nın, Sigortalı'nın sağlık durumuna göre uyguladığı, belirli tıbbi durumların belli bir süre için teminat altında olmadığı süredir.
Önceden Mevcut Hastalık: Bu sigorta sözleşmesinin yapılması için sağlık beyan ve başvuru formunda sorulmuş olmasına rağmen veya sorulmasa dahi Sigortacı'ya beyan edilmeyen, belirtisinin/bulgusunun veya teşhisinin/tedavisinin başlangıcı, sigorta başlangıç tarihi öncesine dayanan rahatsızlıklar ve bunlara bağlı olarak gelişen komplikasyonlardır.
Azami İyi Niyet Prensibi: Sigortacı bu sigorta sözleşmesini ve sözleşme şartlarını Sigorta Ettiren'in beyanına dayalı olarak oluşturmaktadır. Sigorta Ettiren, geçmiş ve mevcut hastalıkları ve sağlık durumuyla ilgili tüm bilgileri tam ve yanılmaya mahal vermeyecek şekilde, gönüllü olarak Sigortacı'ya bildirmekle yükümlüdür.
Başvuru/Beyan ve Bilgilendirme Formu: Sigortalı adayına ait bilgileri (kimlik, iletişim, sağlık beyanı, hesap numarası vb.), tercih edilen poliçe kapsamını (Network, teminat, limit, katılım payı, muafiyet vb.) ve prim ödeme planını içeren, Sigorta Ettiren ve Sigortalı'yı etkileyebilecek nitelikteki değişiklik ve gelişmelerden ilgililerin haberdar edilebilmesini teminen Sigortacı tarafından verilen bilgileri içeren, Sigorta Ettiren ve Sigortalı adayları tarafından doldurulması ve imzalanması gereken formdur.
Coğrafi Bölge: Bu sigorta sözleşmesi ile verilmiş olan teminatların geçerli olduğu bölgeyi ifade eder (Yurt içi/yurt dışı).
Genel Şartlar: T.C. Başbakanlık Hazine Müsteşarlığı tarafından belirlenen ve tüm sigorta şirketleri tarafından sağlık sigortalarında uygulanması zorunlu olan yazılı kurallardır. Genel şartların en güncel hali www.tsb.org.tr adresinde yer almaktadır.
Özel Şartlar: Sigorta şirketi tarafından Sağlık Sigortası Genel Şartları'na ilave olarak hazırlanan, karşılıklı hak ve yükümlülükler ile teminatları ve geçerlilik koşullarını belirten ve bu sigorta sözleşmesinin bitiş tarihine kadar geçerli olan şartlardır.
Endikasyon Dışı İşlemler: Sigortalı'nın sağlığını tehlikeye sokmaksızın hastaneye yatırılmadan da yürütülebileceği tarafsız bir hekim tarafından da kabul edilen tedavi, inceleme ve işlemlerin hastaneye yatırılarak yapılması ve/veya hastanın mevcut tablosu ile uyumlu olmayan ve endikasyonu bulunmayan teşhis ve tedavi işlemlerinin yapılmasıdır.
Kaza: Sigortalı'nın tıbbi olarak kanıtlanabilecek bedensel yara almasına neden olan beklenmedik, ani olayı ifade eder.
Kronik Hastalık: Ani başlangıçlı olmayan, yavaş gelişen ve/veya ilerleyen, zaman zaman tekrarlayan ya da sürekli bir sağlık sorununa neden olan hastalıktır.
Deneysel veya Araştırma Amaçlı İşlem: Hastalığın tanı ve tedavisindeki gereklilik, etkinlik ve güvenilirliğini ortaya koyacak sayıda ve kalitede kontrollü klinik çalışmanın yayınlanmadığı veya yerli ve yabancı otoriteler (FDA, tıp fakülteleri, ilgili kürsü bilim kurulları, Sağlık Bakanlığı, uzmanlık dernekleri vb.) tarafından kabul görmüş olmayan, tıbbi cemiyet veya otoritelerin deneysel aşamada olduğuna dair yazılı bildirimleri tespit edilen veya herhangi bir rahatsızlık olmadan araştırma/kontrol (check-up) amacıyla uygulandığına Sigortacı tarafından karar verilen tetkik ve tedavilerdir.
Doğuştan Gelen Hastalık (Konjenital Hastalık): Belirtileri ileri yaşta ortaya çıksa ve tanısı ileri yaşta konulsa dahi, kromozom anomalileri, genetik bozukluklar, yapısal kusurlar ile prenatal (gebelik öncesi), perinatal (gebelik sırasında) ve doğum eylemi esnasında ortaya çıkabilen fiziksel, metabolik, genetik ve kimyasal nedenlere bağlı oluşan her türlü sakatlık, motor ve mental gelişim bozuklukları, metabolik ve genetik tüm hastalıklar, yapısal anomaliler ve kusurlardır.
Kabul Edilebilir Sağlık Gideri: Sigorta sözleşmesi kapsamında ödeme almak için gönderilen fatura toplamından, varsa kapsam dışı tutar düşüldükten sonra, teminat kapsamında değerlendirilen fatura tutarıdır.
Limit: Sigortacı'nın işbu özel şartlara göre değerlendirdiği ve Sigortacı tarafından kabul edilebilir sağlık gideri ile Sigortalı tarafından ödenmesi gereken katılım payı ve muafiyet tutarlarının toplamını ifade eder.
Katılım Payı: Sigorta sözleşmesi ekinde verilen poliçede belirtilen tutar ya da oranda, kabul edilebilir sağlık gideri üzerinden hesaplanan, Sigortalı'nın üstleneceği miktarı ifade eder.
Kazanılmış Haklar: Bu sigorta sözleşmesinde kazanılmış haklar, Sigortacı tarafından da kabul edilen, İlk Sigortalanma Tarihi ve Ömür Boyu Yenileme Garantisi haklarını ifade eder.
Özel Sağlık Sigortası (ÖSS) Hasta Bilgi Formu: Sağlık Kurumlarından hizmet alınması durumunda Doktor tarafından doldurulması gereken formdur.
Poliçe: Sigorta Ettiren ve/veya Sigortalı ve Sigortacı'nın sigorta sözleşmesinden doğan hak ve yükümlülüklerini gösteren bir belgedir.
Provizyon: Sigortalı'ların tercih etmiş oldukları Anlaşmalı Sağlık Kurumları'nda planlanan muayene, tanı ve tedavileri için ilgili sağlık harcamalarının karşılanıp karşılanmayacağını gösterir, Sigortacı tarafından yapılan değerlendirme sonucudur.
Sigortacı: Bu sigorta sözleşmesinin tanzim edildiği ülkede tescil edilmiş ve işletme ruhsatı almış olan ve bu sigorta sözleşmesini tanzim eden sigorta şirketidir.
Sigorta Ettiren: Bu sigorta sözleşmesi için başvuran, başvurusu Sigortacı tarafından kabul edilen ve bu sigorta sözleşmesinin kapsamı içerisinde sorumlu taraf olup kendisi ve sigortalanacak kişilerin lehine hareket eden kişi veya tüzel kişiliktir.
Sigortalı/Sigortalılar: Poliçede ismi/isimleri belirtilen ve sigorta sözleşmesi ile sağlık giderleri teminat altına alınan ve sağlık giderlerini talep hakkı bulunan kişilerdir.
Referans Doktor: Sigorta sözleşmesi kapsamında değerlendirilecek sağlık giderlerinin tıbbi gerekliliğine dair uzman görüşü alınan ve Sigortacı tarafından belirlenen doktordur.
Sağlık Hizmet Tarifesi: Sağlık hizmeti veren kurumlarda tıbbi hizmet ücretlerinin belirlenmesinde kullanılan birim ve uygulama ilkelerini gösteren referans tarifedir (TTB, HUV, SUT, TDB vb.).
Sağlık Kurumu: T.C. Sağlık Bakanlığı tarafından çalışma ruhsatı verilen, tıbbi bakım ve tedavi hizmeti veren hastane, klinik, poliklinik, muayenehane, teşhis ve tedavi merkezleri ile eczaneleri ifade eder. Otel, huzurevi, bakımevi, nekahethane, yetimhane ve darülacezeler, madde bağımlılığı tedavisi için kullanılan yerler, sanatoryumlar, kaplıcalar, hidroterapi merkezleri ve zayıflama merkezleri bu tanıma girmez.
Teminat Dışı Kalan Haller: Sigorta Sözleşmesi'nin kapsamı dışında tutulan durumlardır.
Yenileme: Sigorta Ettiren'in, mevcut sigorta sözleşmesinin bitiş tarihinden en geç otuz (30) gün içerisinde yeniden sözleşme yaptırmak için Sigortacı'ya başvurması ve koşullarda mutabık kalınmasıyla, sigorta süresinin bitiş tarihinden itibaren yeni koşullarda kesintisiz devam ettirilmesidir.
Zeyil: Poliçe yürürlüğe girdikten sonra, poliçenin yürürlüğü sırasında meydana gelebilecek her türlü değişiklikleri belirten ek sözleşmedir.
Teminat Dışı Kalan Kurumlar: Sigortalı'nın sağlık giderlerinin teminatları gereği kapsam dahilinde olmasına rağmen, geri ödeme alamayacağı kurum ve/veya hekimleri ifade eder (yanlış sigorta uygulamaları, gereksiz tetkik/tedavi, sigorta suistimali tespit edilen kurum/hekimler). Güncel listeye www.aksigorta.com.tr adresinden ulaşılabilir.

3. TEMİNATLAR

3.1 Yatarak Tedavi Teminatı
Poliçe genel ve özel şartları gereği Teminat Dışı Kalan Haller ile Bekleme Süreli durumlar arasında yer almayan yatarak tedavi teminatı kapsamındaki masraflar, varsa muafiyet haricinde, poliçe ekinde yer alan Teminat Tablosu doğrultusunda teminat altındadır. Kapsam dahilinde kabul edilen ve Dünya Sağlık Örgütü (WHO) referans alınarak hazırlanmış Acil Durumlar listesinde yer alan rahatsızlıklara ait giderler, anlaşmalı/anlaşmasız kurum ayrımı olmaksızın bu teminat kapsamında ve Poliçe ekinde yer alan anlaşmalı kurum katılım payı dahilinde ödenir. Trafik kazası tespit tutanağı ve doktor raporu ile belgelenmek kaydıyla, sadece trafik kazası sonucu oluşan ve diş hekimlerince yapılan diş ve çeneye uygulanan her türlü tıbbi ve cerrahi müdahale için oluşacak giderler de teminat kapsamında ödenir. Yatarak Tedavi Teminatı ile Hamilelik ve Doğum Teminatı kapsamında, teminat altına alınan sağlık giderleri için sağlık kurumlarında yatış süresi, yaşam boyu 720 gün, 1 (bir) yıllık sigorta süresi içinde 180 gündür (normal oda yatışları 1 gün, yoğun bakım yatışları 2 gün üzerinden hesaplanır). Ömür Boyu Yenileme Garantisine hak kazanmış sigortalılarda yaşam boyu gün limiti (720 gün) uygulanmaz. Teminat kapsamına giren ve girmeyen ameliyatların bir arada yapılması durumunda, kapsama girmeyen ameliyat/ameliyatlarla ilgili giderler karşılanmaz. Sigortalıların, acil tıbbi durumlar haricinde planlanmış ameliyatları için, ameliyatı yapacak doktor tarafından doldurulacak Özel Sağlık Sigortası Hasta Bilgi Formu'nun, anlaşmalı sağlık kurumu aracılığıyla 48 saat öncesinden Sigortacı'ya gönderilmesi gerekmektedir. Yatış süresi 24 saati aşmayan ve WHO tarafından tanımlanan acil tıbbi durumlar arasında yer almayan tüm giderler varsa ayakta tedavi teminatları kapsamında karşılanır. Kemoterapi, radyoterapi ve diyaliz tedavileri sırasında veya sonrasında tedavinin planlanması, takibi veya hastalığın seyrini değerlendirmek için yapılan muayene ve tetkiklere ait giderler, hastaneye yatış yapılsa dahi ayakta tedavi teminatı kapsamında değerlendirilir.

3.1.1 Dahili Yatış Teminatı: Sigortalının 24 saati aşan hastaneye yatırılarak yapılacak tedavi giderlerinin tıbben gerekli olması ve doktorun bu nedeni ayrıntılı olarak raporunda belirtmesi şartıyla tüm ameliyatsız yatışlar ve fototerapiler, sigortalının hayatı bir tehlikeye neden olabilecek acil sağlık durum giderleri, bu teminat kapsamındadır.

3.1.2 Cerrahi Yatış Teminatı: Sigortalının 24 saati aşan hastaneye yatırılarak yapılacak, tıbbi olarak gerekli olan ve doktor raporunda ayrıntılı olarak cerrahi işlem nedenlerinin belirtilmesi şartıyla ve TTB-HUV Tarifesinde tanımlanan, birimi 200 üzerindeki cerrahi işlemler ameliyat olarak tanımlanır. Ameliyat giderleri (anestezi tetkikleri, ameliyathane kullanım ücreti, operatör doktor, asistan, ameliyat hemşiresi, anestezi giderleri, sarf malzemesi, ilaç, kan/kan ürünleri) ile ameliyat dışındaki ilaç, pansuman, bandaj, alçı, plaster, iğne/serum, doktor takip ve konsültasyon masrafları, hastanede yatan sigortalının hastalığının takibi ve doktorun öngördüğü tedaviyi yönlendirici tetkikleri, tahlil, röntgen masrafları, standart tek kişilik özel oda, yemek ve refakatçi giderleri bu teminattan karşılanır. Mediastinoskopik akciğer biyopsisi, böbrek biyopsisi, karaciğer biyopsileri, beyin biyopsisi işlemleri de bu teminattan karşılanır.

3.1.3 Doktor Ücreti: Yatarak tedavi teminatı kapsamındaki tüm işlemlerde tedaviyi gerçekleştiren doktorun (anestezi ve asistan doktorları dahil), Aksigorta ile anlaşmalı doktor olması veya anlaşmalı kurumun kadrolu doktoru olması durumunda, doktor ücreti sertifikada belirtilen anlaşmalı kurum limit ve katılım payı oranları ile değerlendirilir. Anlaşmasız doktor tarafından yapılması halinde poliçe sertifikasında belirtilen anlaşmasız kurum limit ve katılım oranları uygulanır.

3.1.4 Küçük Müdahale Teminatı: HUV'de 200 biriminin altında kalan girişimler ile müşahede altına alınma, pansuman, enjeksiyon, kulak yıkama, alçı uygulaması, oksijen verilmesi, apse drenajı, mide yıkama, lavman, sonda takma, tırnak çekme, taş kırdırma (ESWL), ortopedide şok tedavisi (ESWT), koterizasyon, ben alımı, eksizyonel yapılan biyopsi işlemleri, PUVA tedavisi, somnoplasti, kriyoterapi uygulaması, derideki yaraların dikişi, gözden yabancı cisim çıkarılması gibi genel/lokal anestezi altında veya anestezisiz yapılan tüm küçük müdahaleler ve sarf malzemeleri, ayakta veya yatarak gerçekleşmiş olmasına bakılmaksızın bu teminat kapsamında değerlendirilir. Omurga ve disk hastalıklarına yönelik uygulanan faset sinir denervasyonu, radyofrekans termokoagülasyon, transforaminal epidural enjeksiyon vb. ağrı tedavilerine ait sağlık giderleri de bu teminat kapsamında ödenir. Ayakta Tedavi Teminatı olmayan poliçelerde, küçük müdahale ile ilgili olsa dahi işlem öncesi/sonrası yapılabilecek tanı amaçlı tetkik ile reçete edilen ilaçlara ait giderler poliçe kapsamında değildir.

3.1.5 Yatış Sonrası Fizik Tedavi Teminatı: Ameliyat ve yoğun bakım gerektiren bir tedaviden sonra, iki (2) ay içerisinde gerçekleşen ve söz konusu tedaviyi tamamlayıcı nitelikteki fizik tedavi masrafları, ayakta ve yatarak gerçekleşmesine bakılmaksızın bu teminat kapsamında değerlendirilir. Tedavinin birden fazla vücut bölgesine uygulanması durumunda her bölge bir (1) seans olarak değerlendirilir.

3.1.6 Rehabilitasyon ve Evde Tıbbi Bakım Teminatları: Sigortalının, nörolojik hastalıklar, ağır travma, el-kol-bacak amputasyonu vb. sonrası yitirdiği yaşam aktivitelerini (koltuk değnekli veya değneksiz yürüme, yeme içme, elbise giyip çıkarma, tuvalete oturma, merdiven inip çıkma) yeniden kazanabilmesi için verilen fonksiyonel eğitim (rehabilitasyon) giderleri, tedavinin yatarak yapılması ve bu durumun Sigortacı tarafından kabul edilmesi koşuluyla teminat kapsamındadır (oda-yemek-refakatçi, doktor takibi vb. giderleri ödenmez). Sigortalının sağlık kurumundaki yatarak tedavisi sonrasında, tedavinin devamı için kendi evinde sadece tıbbi personel tarafından yapılan tıbbi bakım ve tedavilerine ilişkin giderler, poliçe ekinde verilen teminat tablosu doğrultusunda ödenir - bunun için tedavi eden doktorun, taburcu olurken tedavinin bir sağlık personeli eşliğinde evde sürdürülmesi gerektiğini raporla bildirmesi ve Sigortacı'nın önceden onaylaması zorunludur. Evde bakım verilen süre, sağlık kurumunda yatış süresinden düşülür. Rehabilitasyon ve Evde Bakım Teminatı, poliçe ekinde belirtilen limit ve yıllık 60 gün ile sınırlıdır.

3.1.7 Ameliyat Tazminat Teminatı: Sigorta süresi içerisinde ve teminat kapsamında olan ameliyat giderlerinin, Sigortacı'dan talep edilmemesi ve yapılan ameliyatın doktor raporları ile belgelenmesi halinde, Sigortalı'ya ilgili ameliyatın SUT bedeli, poliçe ekinde belirtilen Ameliyat Tazminat Teminatı üst limiti ile ödenir. Aynı ameliyatla ilgili ikinci bir tazminat ödemesi yapılmaz.

3.1.8 Yardımcı Tıbbi Malzemeler Teminatı: Sigorta süresi içinde meydana gelen bir hastalık veya kaza sonucu uygulanan tedavinin bir parçası olarak, vücuda dışarıdan destek olacak şekilde ve sadece tıbbi amaçlarla kullanılan, taşınabilir, kişiye özel atel, ortopedik tabanlık, bot, elastik bandaj, korse, varis çorabı, boyunluk, dizlik, bileklik, tabanlık, oturma simidi, koltuk değneği, tıbbi nebülizatör gibi tıbbi malzemeler, poliçe ekinde yer alan teminat tablosu dikkate alınarak bu teminat kapsamında değerlendirilir.

3.1.9 Suni Uzuv Teminatı: Sigorta süresi içerisinde meydana gelen hastalık ya da kaza sonucu fonksiyon kaybına uğramış organın fonksiyonlarını yerine koyma amacıyla takılan ve estetik amacı taşımayan kalp pili, insulin pompası, el, kol, bacak ve meme kanseri operasyonu sonrası takılan meme protezi olmak üzere protez giderleri, doktor raporuyla belgelenmesi koşulu ile teminat kapsamındadır.

3.1.10 Kontrol Mamografisi: 40 yaş ve üstü kadın sigortalıların, kontrol amaçlı çektirdikleri mamografi ve meme ultrasonografi masrafları, Sigortacı tarafından belirlenen sağlık kurumlarında yılda bir kez ve katılım payı uygulanmadan ödenir.

3.1.11 Kontrol PSA: 40 yaş ve üstü erkek sigortalıların kontrol amaçlı yaptırdıkları PSA tetkik masrafları, yılda bir kez ve katılım payı uygulanmadan ödenir (belirlenen sağlık kurumlarında).

3.1.12 Kemoterapi, Radyoterapi, Diyaliz: Teminat kapsamındaki rahatsızlık nedeniyle yapılan kemoterapi ve radyoterapi giderleri ile diyaliz masrafları, poliçe ekindeki limite kadar bu teminattan karşılanır.

3.1.13 Anjiyografi ve Anjiyoplasti: Koroner damar anjiyografisi ve bu işlem esnasında yapılan tedavi amaçlı anjiyoplasti işlemleri bu teminat altında değerlendirilir.

3.1.14 Yoğun Bakım: Yoğun bakım ünitesinde yapılan tedaviler bu teminat kapsamında karşılanır; yatış süresi gün limitleri her yenilenen poliçe döneminde yeniden başlar.

3.1.15 Oda-Yemek-Refakatçi Teminatı: Yatarak tedavi teminatlarının kullanıldığı durumlarda, tek kişilik odalar için geçerli olmak kaydıyla kullanılabilir. Tek kişilik oda yerine süit oda tercih edilirse aradaki fark sigortalı tarafından karşılanır.

3.2 Acil Sağlık Hizmetleri Teminatları
3.2.1 Tıbbi Danışmanlık: Sigortalı, sağlık sorunları ile ilgili danışmanlık hizmetini, Aksigorta Ambulans ve Acil Tıbbi Yardım Hizmetleri'ni arayarak görevli doktorlar aracılığı ile alabilir.
3.2.2 Ambulans: Acil Durum tanımına uyan hallerde, yerinde müdahale ve/veya bulunduğu yerde tedavinin mümkün olmadığı durumlarda, en yakın sağlık kurumuna nakil için yapılan masraflar Sigortacı'nın onayı ile bu teminattan karşılanır. Karayoluyla ulaştırma mümkün değilse, Sigortacı'nın onayıyla hava veya deniz ambulans hizmeti de verilebilir.

3.3 Annelik Tedavi Teminatı
Hamilelik ve doğum teminat grubu, Sigortalı'nın bu sözleşme kapsamına dahil olmasından en az beş (5) ay sonra başlayacak hamilelikler için geçerlidir (bebek ultrasonografisi ve son adet tarihi (SAT) dikkate alınır; SAT'ın 5 aylık bekleme süresi sonrasında olması gerekir - bu süre tamamlanmadan başlayan hamilelikle ilgili tüm giderler kapsam dışıdır). Hamilelik ve Doğum Teminatı, 18-50 yaş arasındaki kadın sigortalılarda geçerlidir; poliçede "çocuk" konumunda sigortalanmış kişilerde geçerli değildir. Teminat limitsiz alınmışsa vaka (doğum) başına geçerlidir; sözleşme yenilense bile hamilelik ve doğum sonlanana kadar tek limit geçerlidir. Doğum yapıldıktan sonra, aynı poliçe yılı içinde oluşacak ikinci hamileliğe ait doğum ve hamilelik giderleri ödenmez. Doğumun yurtdışında gerçekleşmesi halinde poliçede belirtilen limit kadar ödeme yapılabilir.
3.3.1 Doğum Teminatı: Doğumun sonlandırılması işlemi için yapılan normal doğum veya sezaryen işlemlerine ait doktor ve hastane giderleri ile hamilelik döneminde tıbbi gereklilik halinde amniyosentez işlemi, hamilelik, küretaj, doğum ve sezaryen komplikasyonlarına bağlı yatışlar bu teminat kapsamındadır. Yatarak Tedavi Teminatı ile Hamilelik ve Doğum Teminatı kapsamındaki hastanede yatış süresi, teminat tablosundaki limitlerle sınırlı olmak üzere toplam 180 gündür. Planlanmış doğumlar için, doğumu yapacak doktor tarafından doldurulacak Özel Sağlık Sigortası Bilgi Formu'nun 48 saat öncesinden Sigortacı'ya gönderilmesi gerekir.
3.3.2 Rutin Kontroller Teminatı: Hamileliği ilgilendiren her türlü kontrol muayene ve rutin tetkikler, poliçe ekindeki teminat tablosu dikkate alınarak bu teminat kapsamında değerlendirilir. Muayene tarihinden sonra aynı doktorun 10. güne kadar yaptığı muayenelere ilişkin giderler teminat kapsamı dışındadır (ilave tetkik ya da tedavi önerileri hariç).
3.3.3 Yeni Doğan Masrafı Teminatı: Hamilelik ve Doğum Teminatına hak kazanmış annenin yeni doğan bebeğinin hastaneden çıkmadan yapılan giderleri (yeni doğan bebek muayenesi, kan grubu belirleme, direkt Coombs, neonatal TSH, metabolik tarama testi, bilirubin, otoakustik emisyon/işitme testi, Hepatit B aşısı), anneye ait doğum teminatı limitinden düşülmek kaydıyla teminat kapsamındadır.

3.4 Ayakta Tedavi Teminatları
Teşhis ve tedavinin hastanede yatmayı gerektirmediği hallerde, Sağlık Kurumları'nda yapılan doktor muayene, ilaç, görüntüleme ve laboratuvar işlemleri ile fizik tedavi giderleri poliçe ekindeki teminat tablosu dikkate alınarak bu teminat grubu kapsamında değerlendirilir. Sağlık kurumunda yatış süresi 24 saati aşmayan ve WHO tarafından tanımlanan acil tıbbi durumlar arasında yer almayan tüm sağlık giderleri ile tetkik amaçlı yatışlar bu teminat grubundaki ilgili teminatlar kapsamında karşılanır.
3.4.1 Doktor Muayene Teminatı: T.C. Sağlık Bakanlığınca çalışma ruhsatı verilmiş hastane ve/veya özel muayenehane açmaya ehliyetli doktorlarca yapılacak muayenelere ait giderler, belgelenmesi kaydıyla bu teminat kapsamındadır. İlk muayenedeki tanı ile ilişkili olarak 10. güne kadar yapılan muayeneler kontrol muayenesi olup ücret talep edilmemesi gerekir (bu şekilde faturalandırılmış kontrol muayenesi giderleri teminat dışıdır; ilave tetkik/tedavi önerileri hariç). Sigortacı'nın anlaşmalı hekim muayenesi uygulaması başlattığı illerde, belirlenmiş anlaşmalı hekimlerce yapılacak doktor muayene giderleri teminat limiti kapsamında katılım paysız ödenir.
3.4.2 İlaç Teminatı: Teminat kapsamındaki bir rahatsızlık nedeniyle hekim tarafından reçete edilen, T.C. Sağlık Bakanlığı tarafından ruhsatlı farmasötik ürünler, bir (1) aylık tedavi dozu kadar, doktor reçetesi, ilaç küpürü ya da İlaç Takip Sistemi (İTS) çıktısı ve fiş/fatura asılları ile belgelenmesi koşuluyla teminat kapsamındadır (reçete başına geçerli, reçete bölünemez). Reçete yazıldığı tarihten itibaren en geç on (10) gün içinde ilaçlar alınmalıdır (süre aşılırsa reçete geçersiz sayılır). Kronik hastalıklara ilişkin ilaçlar, sürekli kullanım gerekçesini belirten doktor raporu üzerinde belirtilen ilaçlar için üç (3) aylık tedavi dozları halinde karşılanabilir. 0-6 yaş grubu için tüm çocukluk aşıları ve koruyucu aşılar, yılda bir kez grip aşısı da (alerji aşıları hariç) bu teminat kapsamındadır.
3.4.3 Laboratuvar Hizmetleri: Teminat kapsamındaki bir hastalığın teşhisi ve tedavisi için tıbben gerekli görülen tahliller ile kimyasal madde ve ilaçlara ait giderler, poliçe ekindeki teminat tablosu dikkate alınarak karşılanır. Hepatit markerlerine ait giderler, sadece karaciğer enzim değerlerinin normal değerlerin üzerinde olması durumunda ödenir.
3.4.4 Görüntüleme: Teminat kapsamındaki bir hastalığın teşhisi için tıbben gerekli görülen radyolojik tetkikler, ultrasonografi, mamografi, ilaçlı/ilaçsız grafiler, EKG, eforlu EKG, odyometri, EMG, ürografi, sintigrafi, doppler ve benzeri görüntüleme giderleri bu teminat kapsamında değerlendirilir.
3.4.5 Modern Teşhis Teminatı: Teminat kapsamındaki bir hastalığın teşhisi için doktor tarafından gerekli görülen MR, tomografi, talyum, anjiyografi (koroner anjiyografi hariç), gastroskopi, bronkoskopi, sistoskopi, endoskopi gibi girişimsel tanı yöntemleri, insizyonel biyopsiler bu teminat kapsamındadır.
3.4.6 Fizik Tedavi Teminatı: Teminat kapsamındaki bir hastalığın tedavisi için doktorun gerekli gördüğü fizik tedavi seansları ve rehabilitasyon giderleri, poliçe ekindeki teminat tablosu dikkate alınarak karşılanır. Tedavinin birden fazla vücut bölgesine uygulanması durumunda her bölge bir (1) seans olarak değerlendirilir. Fizik tedavinin sağlık kurumunda yatarak yapılması halinde, fizik tedavi giderleri dışında faturalandırılan oda, yemek, refakatçi, doktor takibi vb. giderler ödenmez.

3.5 Yurtdışı Tedavi Teminatları
3.5.1 Yurtdışı Ayakta Tedavi Teminatı ve 3.5.2 Yurtdışı Yatarak Tedavi Teminatı: Kesintisiz doksan (90) günü geçmeyen yurtdışı seyahatlerinde ve ek prim ödenerek Yurtdışı Tedavi Teminatı'nın alınması şartı ile, poliçe ekindeki Teminat Tablosu doğrultusunda geçerlidir. Yurtdışı seyahatinin kesintisiz 90 günü aşması durumunda, teminat alınmış dahi olsa yurtdışında gerçekleşen sağlık giderleri kapsam dışıdır. Sürekli yatarak tedavi görme hali hariç, yurtdışında kesintisiz 90 günden fazla ikamet eden sigortalıların teminatları, yurtdışında kaldığı 90. günden itibaren durur; Sigortalı'nın Türk Gümrüğü'nden giriş yapmasının ardından teminatlar yeniden başlar. Yurtdışında yapılan tedavilere ait faturalar İngilizce dışında bir dilde ise, Türkçe tercümeleriyle birlikte gönderilmesi gerekir. Türkiye Cumhuriyeti sınırları içinde yapılması tıbben mümkün olmayan ve/veya acil durumlarda, Yatarak Tedavi Teminatı'nın yer alması halinde poliçedeki yıllık limit dahilinde geçerlidir; Türkiye'de tedavisi mümkün olan ve/veya acil olmayan durumlarda ise geri ödeme, yine poliçedeki yıllık limit dahilinde ancak vaka bazlı HUV Tarifesi ile belirlenen tutarın maksimum üç (3) katı ile sınırlıdır.

4. BEKLEME SÜRELERİ
Aşağıda belirtilen durumları kapsayacak şekilde acil olsun/olmasın ilk sigorta başlangıç tarihinden itibaren Hastane Tedavi, Küçük Müdahale, Rehabilitasyon ve Evde Bakım, Ameliyat Tazminat Teminatı, Suni Uzuv ile Fizik Tedavi Teminatları için on iki (12) ay bekleme süresi uygulanır. Sözleşmenin yenilenme koşullarına göre tekrarlanarak sürdürülmesi ve Sigortacı tarafından aşağıda sayılan durumlardan biri için ek şart konmaması halinde, on iki (12) aylık bekleme süresini tamamlayan sigortalılar için aşağıda sayılan bekleme süreleri uygulanmaz ve teminata dahil olur:
1. Lipom, verrü, nevüs vb. deriye yönelik yapılan her türlü işlem, kist (deri-deri altı, böbrek, vajinal vb.), her türlü tümör ve polipler (malign tümörler hariç).
2. Katarakt, glokom, keratoplasti.
3. Bademcik, adenoit, kulak zarı cerrahisi ve tüp uygulaması, sinüs cerrahisi.
4. KOAH, astım, epilepsi, multipl skleroz, hepatit B, sarkoidoz ve tüm romatizmal hastalıklar, bağ dokusu hastalıkları.
5. Benign (iyi huylu) tiroit ve paratiroit bezi hastalıkları.
6. Her türlü fıtık, felç, omurga ve disk hastalıkları (disk hernileri, faset denervasyon, sinir blokajı vb.).
7. Safra kesesi ve safra yolları hastalıkları, karaciğer hastalıkları, kist hidatik, pankreas ve dalak hastalıkları.
8. Ülser, inflamatuar bağırsak hastalıkları (ülseratif kolit, crohn).
9. Her türlü varis, varikosel, hidrosel.
10. Rahim-yumurtalık ve tüplerle ilgili hastalıklar ve ameliyatlar, bartolin kisti, endometriosis, sistosel, rektosel, meme hastalıkları.
11. Anorektal hastalıklar (hemoroid, fissür, fistül, pilonidal sinüs, anal apse vb).
12. Böbrek yetersizliği, diyaliz, böbrek ve idrar yolu ameliyatları, üriner sistem taşlı hastalıklar, prostat (TUR dahil) ve mesane rahatsızlıkları, nefrit.
13. Eklem rahatsızlıkları (kalça, menisküs, bağ lezyonları, omuz, dirsek, ayak bileği eklemlerindeki bağ rahatsızlıkları vb.), her türlü tuzak nöropati, higroma, ganglion, trigger finger hastalıkları.
14. Her türlü organ nakli (kaza sonucu yapılanlar hariç) ve bunların komplikasyonları.
15. Ek prim ödenerek Hamilelik ve Doğum teminatının alınması durumunda hamilelik ve doğum ile ilgili tüm giderler için 5 (beş) ay (Uygulama İstisnası: Hamilelik ve doğum ile ilgili teminatın kullanılabilmesi için Sigortalı'nın ek prim ödeyerek sözleşme kapsamına dahil edilmesi ve son adet tarihinin (SAT) 5 aylık bekleme süresi sonrasında olması gerekmektedir).

5. TEMİNAT DIŞI KALAN HALLER
Sağlık Sigortası Genel Şartları'nda belirtilen teminat dışı hallerle birlikte, aşağıda sayılan haller ve bu sebeple yapılacak her türlü sağlık gideri de (muayene, tetkik, tedavi nüks, komplikasyonlar vb.) teminat kapsamı dışında olup, Sigortalı tarafından karşılanır:
1. Sigortalının sigortacıya sigortalanırken bildirilmiş olsa dahi poliçe başlangıç tarihinden önce var olan şikayet ve hastalıklar ile ilgili her türlü sağlık harcamaları, metastazları, sigortalılık dönemi öncesinde uygulanan ameliyat ve tedavilerin nüks ve komplikasyonları (insizyonel herni, adezyolizis, nüksler, implantların çıkartılması vb.) ve bunlara bağlı olarak gelişen rahatsızlıklar.
2. Poliçe başlangıç tarihinden sonra belirlenmiş olsa dahi tüm konjenital (doğuştan gelen) hastalık ve sakatlıklar/yapı bozuklukları, organ eksiklikleri, deformiteler, Motor ve mental gelişim bozukluğu ile büyüme ve gelişme bozuklukları (Uygulama İstisnası: "Akbebek" olarak kabul edilen bebekler ile Sigortacı'da 5 tam yıl sigortalılık süresini doldurmuş ve Ömür Boyu Yenileme Garantisi hakkı almış Sigortalıların, bu sigortalılık süresinden sonra konulması şartıyla doğuştan gelen hastalıkları ile ilgili tüm giderleri teminat kapsamında değerlendirilir; bu kapsama girmeyen diğer Sigortalılarda ise doğuştan gelen hastalıkların sadece ilk tanısının konulduğu muayene gideri teminat kapsamında değerlendirilir).
3. Genetik hastalıklar, genetik kusurlar ve genetik incelemeler.
4. Genital herpes, genital ve anal papillomatöz lezyonlar, genital siğiller, kondiloma aküminata, HPV enfeksiyonları, genital ve anal molluscum contagiosum, sifilis, gonore.
5. HIV virüsü enfeksiyonları, AIDS.
6. Ruh ve sinir hastalıkları, psikoterapi, psikiyatrist ve psikolog giderleri ile danışmanlık hizmetleri, tüm psikiyatrik ilaçlar ve bu ilaçların kullanımına bağlı komplikasyonlar ile tüm psikiyatrik yatışlar, zekâ testi ve benzeri tetkikler, geriatrik tedavi giderleri, alzheimer, parkinson, demans hastalığı, nöropsikiyatrik testler, psikososyal bozukluklar (gece işemeleri gibi) ile ilgili giderler, ses ve konuşma terapileri.
7. Alkol zehirlenmesi, alkolizm, alkol kullanımı sonucu doğan rahatsızlıklar ve kazalar, eroin, morfin veya benzeri uyuşturucuların kullanılması ve bunlardan herhangi birinin bünyelerinde mevcut olduğu tespit edilen Sigortalı'nın hastalık, kaza ve yaralanmaları, yoksunluk sendromu sonucu oluşabilecek her türlü gider.
8. Dağcılık, paraşütle atlama, rodeo, yamaç paraşütü, planör, rafting, sokak kızağı, yükseltten atlama sporları, uçurtma ile yapılan sporlar (kiteboarding, kitesurfing gibi), su altı sporları, mağara dalgıçlığı, dağ bisikleti, motosiklet ve otomobil sporları ve bunlarla sınırlı olmayan diğer tehlikeli faaliyetler ile ilgili her türlü gider, profesyonel sporcu lisansına sahip kişilerde her türlü müsabaka ve/veya antrenman sonucu meydana gelebilecek hastalık ve/veya sakatlıklara ilişkin her türlü sağlık gideri.
9. Sigortalı'nın ehliyetsiz araç kullanımı sonucu olan kazalarının gerektirdiği tedavi masrafları.
10. Tanımlamalar kısmında belirtilen endikasyon dışı işlemler ve gereksiz hastane tedavisi işlemleri.
11. Uyku apnesi ve horlama ile ilgili tüm tetkik ve tedaviler, uyku apnesi tedavisi için kullanılan her türlü aparey vb.
12. Belirli bir semptom ve/veya hastalığa bağlı olmadan yapılan işlemler, poliçe kapsamında check-up teminatı olmadığı durumlarda check-up giderleri.
13. Ailevi risk faktörleri nedeniyle oluşacak her türlü gider, karaciğer enzim değerlerinin normal değerleri üzerinde olmadığı durumlarda yapılan Hepatit tetkiki giderleri.
14. Yurtdışı teminatı seçilmediği durumlarda yurtdışında gerçekleşen her türlü sağlık gideri.
15. Poliçe geçerlilik süresinde trafik kazası sonrasında oluşmadığı sürece diş, diş eti ile ilgili tüm giderler, çene eklemi, ağız çene cerrahisi, çene kemiği ile ilgili yapılan tüm muayene, ilaç giderleri ve tüm işlemler (trafik kazasının trafik zaptı ile belgelendirilmesi zorunludur).
16. Tıbbi ve yardımcı tıbbi malzeme statüsünde değerlendirilemeyecek her türlü alet, cihaz ve bu cihazlara ait alet kullanım bedeli, alet-cihaz kira bedeli (robotik cerrahi için robot kullanımı-kira ücreti gibi) ile ilgili tüm giderler, her türlü protez tamiri.
17. Organ ve kan naklinde vericinin masrafları, organ ücreti ve organın ulaştırılması masrafları.
18. Sigorta Sözleşmesinin geçerlilik süresinde meydana gelen bir kaza veya hastalık nedeniyle ortaya çıkan bir kusurun düzeltilmesine yönelik olanların dışındaki tüm estetik ve plastik cerrahi işlemler, trafik kazası dışında diş ve burun ile ilgili estetik ve plastik cerrahi işlemleri (trafik kazasının trafik zaptı ile belgelendirilmesi zorunludur).
19. Yüzeysel varis tedavisi, kimyasal blokaj.
20. Estetik amaçlı aşı ve enjeksiyonlar, kozmetik ve estetik tedaviler, mezoterapi, anti-aging merkezlerinde yapılan tüm işlemler, ksantelezma, göz kapağı ve çevresi estetiği ile ilgili her türlü gider. Estetik ve güzellik merkezlerinde yapılan tüm muayene, tetkik ve tedavi giderleri, jinekomasti ile ilgili her türlü gider, her türlü meme küçültme ve büyütme ameliyatı ile ilgili gider, nazal valv girişimleri ile ilgili giderler.
21. Saç dökülmesi ile ilgili tetkik, tedavi ve ilaç giderleri, telenjektazi, hiperhidrozis (aşırı terleme) cilt hemanjiyomlarına yönelik tedaviler.
22. Doktor nezaretinde yapılmış olsa dahi kaplıca, termal, otel ve benzeri tesislerde yapılan her türlü kür, rehabilitasyon, fizik tedavi giderleri.
23. Obezite (ilaç, diyetisyen ve yağ kitle ölçüm testleri dahil), kilo kontrol bozuklukları tedavisi (şişmanlık veya zayıflık), her türlü mide küçültme ameliyatları, anoreksiya, masaj, diyet, jimnastik salonları, zayıflama merkezleri vb. konularla ilgili giderler ve gıda intolerans tetkikleri.
24. Karyopraktik tedaviler ve PRP işlemi.
25. Alternatif tıp merkezlerinde yapılan muayene ve tüm tedavi giderleri (akupunktur, homeopati, hidroterapi, jakuzi, hipnoz, ayurveda vb.), tanı/tedavideki gereklilik, etkinlik ve güvenilirliğini ortaya koyacak sayıda ve kalitede kontrollü klinik çalışmanın yayınlanmadığı veya otoritelerce kabul görmemiş, deneysel/araştırma niteliğindeki her türlü işleme ait tüm giderler.
26. Gözdeki kırma kusuruna yönelik her türlü cerrahi tedavi, keratokonus, şaşılık, görme tembelliği.
27. İşitme kusuru tedavisi ve cerrahisi (kronik otit sekeli, kulak zarı onarımı hariç).
28. Kürtaj, infertilite (kısırlık), düşük araştırması ve hamileliğin gerçekleşmesinin sağlanması ile ilgili tüm tetkik ve tedavi giderleri (tüp bebek, follikül takibi, spermiyogram, adhezyolizis, mikro-enjeksiyon, tuboplasti, AMH vb.), histerosalpingografi (HSG).
29. Cinsel işlev bozuklukları, peyroni hastalığı ilgili tüm tetkik ve tedavi.
30. Erken doğan bebeklerde erken doğum nedeniyle oluşan ve prematürite ile ilgili tüm giderler.
31. Poliçe ekinde verilen teminat tablosunda ilgili teminatın yer almaması durumunda hamilelik ve doğum ile ilgili tetkik, tedavi ve komplikasyon giderleri.
32. Alerjiye yönelik testler ve aşılanmalar (solunum fonksiyon testi, IgE ve serumda total eozinofili testleri hariç).
33. Herhangi bir sebep/kaza sonucu (trafik kazası hariç) oluşsa dahi nazal septum deviasyonu ve konka hipertrofisi (Uygulama İstisnası: Sigortacı'da Ömür Boyu Yenileme Garantisi hakkı elde etmiş olan ve ilk sigortalanma tarihinden itibaren beş (5) tam yıl sigortalılık süresini tamamlamış kişilerde tanının, Aksigorta'da sigortalanma tarihinden sonra konulması şartı ile Septum Deviasyonu ve Konka Hipertrofisi kapsam dahilinde değerlendirilir).
34. Tetanos, kuduz ve 0-6 yaş grubu koruyucu ve çocukluk aşıları ile yılda bir kez grip aşısı haricindeki tüm aşılar ve diğer koruyucu hekimlik uygulamaları.
35. Koroner Arter Kalsiyum Skorlama Testi, Koroner CT Anjiyo, EBT (Elektron Beam Tomografi), sanal anjiyo, sanal kolonoskopi ve buna benzer tarama amaçlı yapılan tetkiklere ait giderler.
36. Her türlü çocuk maması, çocuk bezi, biberon, emzik vb. çocukla ilgili sarf malzemeleri, tıbbi gereği olsa dahi sünnetle ilgili tüm masraflar.
37. Alkol, kolonya, her türlü sabun, şampuan, saç losyonları, lens solüsyonları, diş macunu, termometre, şeker ölçme stikleri ve kartuşları, buz kesesi, sıcak su torbası, tatlandırıcı vb. yardımcı tıbbi malzemeler, nemlendirici amaçlı ürünler, kozmetik amaçlı ürünler, T.C. Sağlık Bakanlığı tarafından ruhsatlandırılmamış ilaçlar ve gıda takviyesi ve her türlü ilaç formunda hazırlanmış bitki ve bitki ekstresi ve distilat vb. içeren ürünler, gözlük, çerçeve, kontak lens giderleri.
38. Skolyoz, Kifoz, Halluks Valgus (Uygulama İstisnası: Sigortacı'da Ömür Boyu Yenileme Garantisi hakkı elde etmiş olan ve ilk sigortalanma tarihinden itibaren beş (5) tam yıl sigortalılık süresini tamamlamış kişilerde tanının, Aksigorta'da sigortalanma tarihinden sonra konulması şartı ile Halluks Valgus kapsam dahilinde değerlendirilir).
39. 0-7 yaş arasındaki çocukların kordon kisti, hidrosel, her türlü fıtık işlemleri ile ilgili giderler (Uygulama İstisnası: "Akbebek" olarak kabul edilen bebeklerde doğuştan gelen hastalıklar ile ilgili istisna geçerlidir).
40. Resmen ilan edilmiş olan salgın hastalıklar ve karantina ile ilgili giderler.
41. Sigortalı ile akrabalık bağı olan hekimler tarafından düzenlenen faturalar.
42. Kordon kanı ve kök hücre alınması, saklanması ile ilgili giderler.
43. Sigortalı'nın vefatı halinde cenaze işlemleri ile ilgili giderler (morg, cenaze nakli vb.), Sigortalı'nın hastalık ve/veya rahatsızlık sonucu çalışamaması nedeniyle elde edemediği kazançlar için günlük iş görememe parası.
44. Sigortacı tarafından onaylanmış Evde Bakım Teminatı dışındaki, Sigortalı'nın bakıma ihtiyaç duyması halinde, gündelik bakım parası.
45. Sigortacı tarafından teminat kapsamında değerlendirilerek kabul edilen ambulans hariç her türlü ulaşım gideri.
46. Evlilik öncesi, işe başlama öncesi, spor öncesi vb. nedenler ile alınan sağlık kurulu raporu için yapılan giderler.
47. AKSİGORTA A.Ş.'ye ait www.aksigorta.com.tr adresli web sayfasında ''Online İşlemler'' adımı altında bulunan 'Teminat Dışı Kalan Kurumlar Listesi''nde yer alan kurumlara ve doktorlara ait her türlü gider.
Sigortacı, teknolojik gelişmeleri ve yeni uygulamaya alınan tedavi yöntemlerinin hayati öneme sahip olup olmamasına ve alternatif tedavi yöntemlerinin bulunup bulunmamasına bağlı olarak kapsama alıp almamaya yönelik "Teminat Dışı Kalan Haller ve İstisnai Durumlar" başlığı altında düzenlemeler yapabilir. Bu değişiklikler, Ömür Boyu Yenileme Garantisi hakkı bulunan Sigortalılar dahil olmak üzere her bir Sigortalı için yeni poliçe başlangıç tarihinden itibaren geçerli olur.

6. COĞRAFİ KAPSAM
Bu sigorta sözleşmesi ile verilen teminatlar, Yurtdışı Tedavi Teminatı hariç, Türkiye Cumhuriyeti ve Kuzey Kıbrıs Türk Cumhuriyeti (K.K.T.C.) sınırları içinde geçerlidir.

7. TEMİNAT UYGULAMA ESASLARI
Sigorta Ettiren'in seçtiği plana esas olmak üzere, sözleşmenin kapsamı: (a) Sigorta Sözleşmesinin şartları, teminat dışı kalan haller, bekleme süreleri ile poliçe ekinde verilen teminat tablosu; (b) bütün teminat ve hizmet düzeylerinde uygulanabilen özel şartlar ve (varsa) özel istisnalar, Limit, katılım payı ve/veya muafiyetler dikkate alınarak belirlenir. Sigortalı'nın kabul edilebilir tazminat taleplerinin, bu Sigorta Sözleşmesi süresi içerisinde gerçekleşmiş olması gerekir. Poliçe ekinde yer alan teminat tablosunda belirtilen sigorta teminatları, sadece poliçe kapsamında yazılı Sigortalılar için ayrı ayrı geçerli olup, bunun dışındaki kişiler sigorta teminatlarından yararlanamazlar.

8. TAZMİNAT ÖDEMESİ
8.1 Anlaşmalı Sağlık Kurumları: Anlaşmalı Sağlık Kurumu'nda yapılacak sağlık giderleri için, teminat tablosundaki limit, katılım payı ve muafiyet doğrultusunda, doğrudan Anlaşmalı Sağlık Kurumu'na Sigortacı tarafından ödeme yapılacağına dair provizyon verilir. Provizyon sırasında verilen ön onay, Sigortacı'nın onay konusu teşhis ve tedavi işleminin yapılması sonrasında buna ilişkin sağlık giderlerini yeniden değerlendirmesine engel değildir. Sigortalı, Anlaşmalı Sağlık Kurumu'nda Sigortalı olduğunu belirtmek, T.C. kimlik numarasının yazılı olduğu resimli kimlik belgesini ibraz etmek ve teminat tablosunda belirtilen katılım payı, muafiyet tutarı ve limit üzerinde kalan tutarı ödemekle yükümlüdür.
8.2 Anlaşmasız Sağlık Kurumları: Anlaşmasız Sağlık Kurumu olarak tanımlanan kişi ve kurumlarda gerçekleşen sağlık giderleri öncelikle Sigortalı tarafından ödenir; belgeler Sigortacı'ya ulaştıktan sonra Özel Şartlar ve Sağlık Sigortası Genel Şartları ile teminat tablosuna göre değerlendirme yapılır. T.C. Sağlık Bakanlığı'na bağlı devlet hastaneleri ve devlete ait üniversite hastanelerinde gerçekleşen tüm işlemlere ait sağlık giderlerinin karşılanması, Anlaşmalı Sağlık Kurumları'nda geçerli olan limit, katılım payı ve muafiyet oranında yapılır.
8.3 Sağlık Giderlerinin Belgelendirilmesi: Anlaşmasız Sağlık Kurumları'nda gerçekleşen (ya da anlaşmalı kurum olsa bile öncelikle Sigortalı'nın ödediği) sağlık giderlerinin geri ödenebilmesi için gerekli evrakların (Özel Sağlık Sigortası Hasta Bilgi Formu, fatura asılları ve ayrıntılı dökümleri, ameliyat/epikriz raporu, tetkik sonuçları, adli olay belgeleri, yurtdışı belgelerin Türkçe tercümeleri, trafik kazası tespit tutanağı vb.) Sigortacı'ya ulaştırılması gerekir. Anlaşmasız Sağlık Kurumları'ndaki giderlerde tazminat ödemeleri, başvuru formunda bildirilen banka hesabına, gerekli tüm bilgi ve belgelerin Sigortacı'ya ulaştığı tarihten itibaren en geç 10 (on) iş günü içinde yapılır. Sigortalının oluşan sağlık giderine üçüncü şahısların neden olması halinde, Sigortacı ödediği tazminat tutarını üçüncü şahıslara rücu edebilir.

9. SÖZLEŞMENİN YENİLENMESİ VE SÖZLEŞMEDE ÖMÜR BOYU YENİLEME GARANTİSİ VERİLMESİ
9.1 Sözleşmenin Yenilenmesi: Yenileme, Sigorta Ettiren'in mevcut sözleşmenin bitiş tarihinden en geç otuz (30) gün içerisinde yeniden sözleşme yaptırmak için Sigortacı'ya başvurması ve koşullarda mutabık kalınmasıyla, sigorta süresinin bitiş tarihinden itibaren kesintisiz olarak devam ettirilmesidir. Yeniden sözleşme başvurusunun bu şartlarda yapılmaması halinde, ÖBYG hakkı ve standart bekleme süresi için önceki sigortalılık süresi dikkate alınmaz, kayıt tarihi için yeni başvuru tarihi esas alınır. Sigortacı, yenileme döneminde sözleşmeyi hiç yenilemeyebileceği gibi, Sigortalı'nın mevcut rahatsızlıkları/hastalıkları için ek şartlar (muafiyet, limit, ek prim, katılım, bekleme süresi vb.) uygulayarak da yenileyebilir. Yenilenen sigorta sözleşmesi, kural olarak biten sözleşme ile aynı teminat yapısına sahip aynı sigorta ürünü olmalıdır.
9.2 Ömür Boyu Yenileme Garantisi (ÖBYG): Sigortacı, aşağıdaki hüküm ve şartlara göre Ömür Boyu Yenileme Garantisi hakkı verebilir. Bu hak, Sigortalı'nın primini düzenli ödeyerek sözleşmelerini düzenli olarak yenilemesi ve Sigortacı'nın risk kabul uygulamaları ile poliçenin yenileme tarihinde geçerli özel şart hüküm ve koşulları doğrultusunda yapılan risk değerlendirmesi sonucunda verilir. ÖBYG hakkı alındıktan sonra, Sigortacı bu kişinin değişen sağlık koşullarına göre risk değerlendirmesi yapmaz ve ek şartlar (muafiyet, limit, ek prim, katılım, bekleme süresi vb.) uygulamaz - ancak Sigortalı'nın ÖBYG hakkı öncesine ait bilinmeyen bir sağlık riskinin tespit edilmesi durumunda veya sigorta ürünü/anlaşmalı sağlık kurum ağı/teminat kapsamını genişletmek istediği takdirde, Sigortacı ÖBYG hakkını yeniden değerlendirir. ÖBYG hakkı, Sigortalı'nın Sigortacı'da kesintisiz üç yıl sigortalı kaldığı ve bu süre içinde "Azami İyi Niyet Prensibi" ilkesine uygun davrandığı durumlarda, Risk Değerlendirme Birimi tarafından yapılacak tıbbi ve teknik değerlendirme sonucuna göre verilebilir. Sigortacı'nın bu hakkı vermeme veya ek şartlarla verme hakkı saklıdır. ÖBYG hakkı kişiye özel bir hak olup, bu hakkı kazanmış Sigortalıya aittir. Sigorta sözleşmesi kapsamında teminat altına alınan sağlık giderleri için sağlık kurumlarında yatış süresi, yaşam boyu 720 gün, bir (1) yıllık sigorta süresi için ise 180 gündür. ÖBYG hakkı kazanmış olan sigortalılarda yaşam boyu gün limiti (720 gün) uygulanmaz.

10. PRİM TESPİTİ
İlk defa sigortalanacak kişilerin prim tespitinde, ürün tarife fiyatı baz alınır. Aynı planda kalmak suretiyle poliçesinin yenilenmesine karar verilen kişi için yenileme primi, aynı yaş ve cinsiyetteki ilk defa sigortalanacak sağlıklı bir Sigortalı için geçerli olan tarife fiyatının beş (5) katını geçemez.
10.1 Primin Tespitine İlişkin Kriterler: Poliçe primi tespitinde; Sigortalı'ların yaş ve cinsiyeti, kronik/kritik hastalıkları gibi sağlık riskleri, poliçe kapsamındaki teminat ve teminat limit tutarı, teminat şekli, anlaşmalı kurum, Sigortalı katılım payı yüzdesi, muafiyet tutarı, teminatın kullanım frekansı, tazminat/prim oranları, coğrafi bölge ve medikal enflasyon gibi hususlar dikkate alınmaktadır.
10.2 Tarife Primi: Bilimsel kabul görmüş ya da şirketin tecrübe edilen aktüeryal metodolojileri baz alınarak hesaplanan baz primdir.
10.3 Poliçe Primi: Tarife primleri baz alınarak, dönemsel indirimler hariç tanımlanmış ek prim ve/veya indirimlerin uygulanması sonucunda kişiye özel belirlenen primdir.
10.4 Toplam Poliçe Primi: Poliçe primleri baz alınarak tüm dönemsel indirimlerin uygulanması sonucunda kişiye özel belirlenen ödenecek primdir.
10.5 Prime İlişkin Düzenlemeler:
10.5.1 Tazminat/Prim (T/P) Oranına Bağlı İndirim/Ek Prim Uygulaması: Sona eren ve yenilenecek poliçenin sadece yatarak tedavi veya yatarak ve ayakta tedavi teminatlarını içeriyor olması şartı ile, son yılın Ödenen Tazminat/Ödenecek Poliçe Primi (T/P) oranının değerlendirilmesi sonucu, aşağıdaki koşul ve oranlarda indirim ve/veya ek prim uygulanabilir: T/P oranı %0-%10 arası ise -%40 indirim; %10-%25 arası -%25; %25-%50 arası -%10; %50-%100 arası %0; %100-%120 arası %10 ek prim; %120-%150 arası %20 ek prim; %150-%175 arası %30 ek prim; %175-%200 arası %40 ek prim; %200 üzeri %50 ek prim. (40 yaş üstü kadınlarda kontrol mamografi/meme ultrasonografisi ve 40 yaş üstü erkeklerde kontrol PSA tetkik masrafları için ödenen tazminatlar bu hesaplamada dikkate alınmaz. Hamilelik ve Doğum Teminatı içeren planlarda T/P oranına bağlı indirim/ek prim uygulanmaz.) Sadece Yatarak Tedavi Teminatı bulunan poliçelerde: birinci yılın sonunda T/P oranı %0 ise %10 indirim; ikinci ve üstü yıllarda T/P oranı %0 ise %20 indirim uygulanır (ÖBYG hakkı olan sigortalılar T/P'ye bağlı ek primden muaftır).
10.5.2 Risk Ek Primi: Tarife priminden bağımsız olarak, Sigortalı adayının bireysel sağlık durumunun değerlendirilmesi sonucunda sigorta güvencesinin sağlanabilmesi için ödenmesi gereken ek primdir; aynı yaş ve cinsiyetteki sağlıklı bir Sigortalı için geçerli tarife fiyatının üç (3) katını geçemez.
10.5.3 Geçiş İndirimi: Sigortalı'nın bir önceki sigorta şirketinde sona eren sözleşmesinin ve Sigortacı ile yapacağı sözleşmenin yatarak ve ayakta tedavi teminatlarını içeriyor olması şartı ile, son yılın Ödenen Tazminat/Poliçe Primi (T/P) oranına göre geçiş indirimi verilir: son yıl T/P oranı %0-%25 için %20 indirim; %26-%45 için %15 indirim; %46-%60 için %10 indirim.
10.5.4 Ödeme Planı İndirimi: Poliçe priminin, Sigortacı tarafından belirli kurallar veya kampanyalar çerçevesinde belirlenen vadelerde ödenmesi durumunda uygulanacak indirimdir.
10.5.5 Aile İndirimi: Anne, baba ve 24 yaşına kadar olan çocukların aynı poliçe kapsamında sigortalanması halinde, kişi sayısı dikkate alınarak uygulanan indirimdir.
10.5.6 Diğer İndirimler ve Ek Primler: Sigortacı tarafından dönemsel olarak düzenlenecek kampanyalar kapsamında ve benzeri durumlarda, işbu özel şartlarda tanımlanan indirim ve ek primler dışında yapılan her türlü indirim ve ek primi ifade eder.

11. SİGORTAYA KABUL UYGULAMALARI
Bu sigorta ile, Türkiye Cumhuriyeti sınırları içerisinde ikamet eden, 0-65 yaş aralığındaki kişiler sigortalanabilmektedir. 0-18 yaş aralığındaki kişiler, Sigorta Ettiren'in 18 yaş üstü olması kaydıyla tek başına sigortalanabilirler. Aynı poliçe kapsamında, aile tanımına uyan anne, baba ve tam gün üniversitede okuyan ve serbest ya da ücretli çalışmayan 25 yaşından küçük çocuklar sigortalanabilir.
11.1 Yeni Giriş İşlemleri: Sigorta Sözleşmesi için yapılacak her türlü başvurunun yazılı ve imzalı olması şarttır. Sigorta Ettiren/Sigortalı, teklifnamede ve tamamlayıcı belgelerde kendisine sorulan sorulara doğru cevap vermek ve riziko değerlendirmesine etkisi olacak hususları beyan etmekle yükümlüdür. Sağlık beyanı gerçeğe aykırı veya eksik/yanıltıcıysa, 6102 sayılı Türk Ticaret Kanunu'nun 1435. ve Sağlık Sigortası Genel Şartları 6. maddesi hükümleri uygulanır; Sigortacı, riziko gerçekleşmiş olsa dahi ek şart uygulama, sözleşmeyi yapmama ya da yapmış ise cayma hakkına sahiptir. Bu durumda riziko gerçekleşmiş ise Sigortalı'ya tazminat ödenmez, Sigortacı prime hak kazanır.
11.1.2 Yeni Giriş İşlemleri (yıl içinde): Yürürlükte olan sözleşmeye, yıl içerisinde yeni sigortalı girişi ancak evlenme nedeniyle eşin dahil edilmesi, doğum nedeniyle yeni doğan bebeğin dahil edilmesi, evlat edinilmesi nedeniyle çocuğun dahil edilmesi durumlarında Sigortacı'ya başvuru yapılması halinde mümkündür. Poliçeye eklenecek kişilerin primleri, yıllık prim üzerinden gün esasına göre hesaplanarak alınır.
11.1.3 Yeni Doğan Bebeklerin Poliçeye Girişi: Sigortalı annenin doğum esnasında yürürlükte poliçesi bulunuyor olması kaydıyla bebek doğum tarihinden itibaren 60 gün içerisinde hastane taburculuk sonrası sağlık beyan ve başvuru formu doldurularak taburculuk epikriz raporu ile Sigortacı'ya bildirilmesi ve yapılacak olan risk değerlendirmesi sonucu poliçeye eklenerek, belirlenen priminin ödenmesi kaydıyla "Ak Bebek" olarak doğum tarihi itibariyle kabul edilebilecektir. Bu bebekler için poliçe özel şartlarında yer alan bekleme süreleri uygulanmayacak ve poliçeye giriş tarihi itibari ile Ömür Boyu Yenileme Garantisi hakkı verilebilecektir. "Ak Bebek" tanımı yapılmış ve ÖBYG hakkı verilmiş bu bebeklerin, doğuştan gelen hastalık ve sakatlıkları da teminat kapsamında olacaktır. Annenin doğum için hastaneye yatışından bebeğin taburcu oluşuna kadar gerçekleşen, bebeğe ait tüm sağlık giderleri ilgili teminatı mevcutsa Teminat Tablosunda belirtilen Yeni Doğan Bebek Teminatı üst limiti ile ödenir. Bebeğin doğum giderleri Sigortacı tarafından ödenmiş dahi olsa, her ne sebeple olursa olsun bebek doğum tarihi itibari ile iki ay içinde sağlık beyan ve başvuru formu doldurularak Sigortacı'ya bildirilmemiş ve bu süre içinde prim ödemesinin yapılmaması durumunda, poliçeye eklenmesi talep edilen bebekler "AkBebek" olarak kabul edilmeyecek olup, yeni doğan bebek için tüm sağlık riskleri göz önüne alınarak risk değerlendirmesi yapılacaktır - bu durumda çocuklar için ilk yıl sigortalılık şartları (bekleme süreleri) geçerli olacaktır.

12. GEÇİŞ İŞLEMLERİ VE KAZANILMIŞ HAKLAR
Diğer sigorta şirketlerinde herhangi bir Sağlık Sigorta Poliçesi kapsamında bulunan kişilerin, diğer sigorta şirketinden ayrılarak Sigortacı'dan sağlık sigortası almak istediği durumlarda, sigortalı olduğu önceki şirketinden kazanılmış haklarını gösteren belgelerin Sigortacı'ya iletilmesi gerekmektedir. Diğer sigorta şirketindeki poliçe bitiş tarihini takip eden ilk otuz (30) gün içerisinde Sigortacı'ya Başvuru, Beyan ve Bilgilendirme Formu doldurularak başvurması gerekmektedir; Risk Değerlendirme Birimi tarafından yapılacak değerlendirme sonucu, Sigortacı ile Sigorta Ettiren'in yeni sigorta sözleşmesinin koşullarında mutabık kalması durumunda kişilerin 30 gün içinde sigortalanması şartı ile kazanılmış hakları korunabilecektir. Önceki sigorta şirketinde kazanılmış olsa dahi, geçiş yapma talebinde bulunan Sigortalı adayı için Risk Değerlendirme Birimi tarafından yapılacak medikal ve teknik değerlendirme sonucuna göre ÖBYG hakkı korunabilecektir; önceki şirkette teminat kapsamında olan ancak Sigortacı'nın tercih edilen sigorta ürününde bulunmayan teminat ve hizmetler kapsam dışında kalacaktır. Geçiş sırasında Sigortalı adayının hamilelik durumu olsun ya da olmasın Doğum Teminatı ile Hamilelik ve Rutin Kontroller Teminatları için Poliçe Özel Şartları'nda belirtilen bekleme süreleri her durumda geçerli olacaktır. Önceki sigorta şirketinde kapsam dahilinde olsa dahi rahatsızlıkları için risk analizi yapılır, kazanılmış hak kapsamına alınmaz; başvuru formundaki sağlık beyanı ve hastalık riskleri, geçiş bilgilerinde belirtilen tazminat/prim oranları, hastalık riskleri ve ilk kayıt tarihi bilgileri çerçevesinde risk değerlendirmesi yapılarak poliçe kabul koşulları belirlenir.

13. SİGORTA SÜRESİ VE SİGORTA SÖZLEŞMESİNİN SONA ERME ESASLARI
13.1 Sigorta Süresi: Sigorta sözleşmesinin yürürlükte olduğu dönemi ifade eder. Sigortanın süresi 1 yıldır ve poliçede belirtilen başlangıç ve bitiş tarihleri arasında yürürlükte kalır (poliçe üzerinde belirtilen başlangıç tarihinde saat 12.00'de başlar, bitiş tarihinde saat 12.00'de sona erer). Bu sigorta sözleşmesi yürürlükteyken başlayan ve kesintisiz olarak sigorta sözleşmesinin bitiş tarihinden sonraki bir tarihe kadar süren hastane tedavilerinin masrafları, sigorta süresinin sona ermesiyle yeni bir sözleşme yapılmaması durumunda, sigorta sözleşmesinin bitiş tarihinden itibaren 15 güne kadar teminat altındadır. Sigorta sözleşmesinin iptali veya Sigortalı'nın sigorta sözleşmesi teminatlarından çıkarılması halinde iptal, çıkartılma veya ürün-plan değişikliği tarihinden sonraki hastane tedavilerinin masrafları hiçbir koşul aranmaksızın karşılanmaz.
13.2 Sigortacı Sorumluluğunun Başlaması: Sigorta teminatları, başvurunun Sigortacı tarafından onaylanması ve poliçe priminin tamamının veya taksitli ödenmesi kararlaştırıldıysa ilk taksitinin ödenmesi ile yürürlüğe girer.
13.3 Sözleşme İptalleri ve Poliçeden Çıkış İşlemleri:
- Kötü Niyet Sonucu İptal: Sigortalı veya Sigorta Ettiren'in kötü niyetli hareketlerinin ve eksik beyanının saptanması durumunda, Sigortacı teminat kapsamında yaptığı sağlık gideri ödemelerini faiz ve masrafları ile birlikte geri alma ve poliçeyi prim iadesi yapmaksızın iptal etme hakkına sahiptir.
- Primin Ödenmemesi Sonucu İptal: Sigortalı ettiren, sigorta primini veya primin taksitle ödenmesi kararlaştırıldığı takdirde peşinatını, sigorta poliçesinin teslim edildiği günün bitimine kadar ödemediği takdirde temerrüde düşer. Aynı şekilde, sigorta ettiren, kesin vadeleri poliçe üzerinde belirtilen prim taksitlerinin herhangi birini vade günü bitimine kadar ödemediği takdirde temerrüde düşer. Prim ödeme borcunda temerrüde düşülmesi halinde Türk Ticaret Kanunu hükümleri uygulanır.
- Sigorta Ettiren/Sigortalı Talebi Sonucu İptal: Sigorta Ettiren, sigorta sözleşmesini herhangi bir sebep göstermeksizin, yazılı yapacağı fesih ihbarı ile feshetme hakkına sahiptir; fesih Sigortacı tarafından ihbarın tebellüğ edildiği tarihte hüküm doğurur. Poliçenin tanzim tarihinden itibaren ilk 30 gün içerisinde kanuni sebepler dışında iptal talebinde bulunulması halinde, riziko gerçekleşmediği durumlarda ödenen primler kesintisiz olarak iade edilir; 30 günlük sürenin aşılması halinde riziko gerçekleşmediği durumlarda poliçe gün esası üzerinden iptal edilir. Ödenen tazminatlar, Sigortacı'nın hak kazandığı prim tutarını aşmıyorsa, ödenen primden hak kazanılan prim tutarı düşülerek Sigorta Ettiren'e iade edilir; aşıyor ancak ödenen primleri aşmıyorsa, primlerden tazminat tutarı düşülerek iade edilir; sözleşmede öngörülen toplam prim tutarını aşıyorsa prim iadesi yapılmaz.
- Vefat Durumu: Sigorta Ettiren'in vefatı durumunda sigorta sözleşmesi hükümsüz kalır. Sigorta Ettiren'in Sigortalı olarak poliçede yer almadığı durumda kanuni vârislerin vereceği muvafakatname ile Sigorta Ettiren değiştirilerek poliçe devam ettirilir; onay olmaması halinde Sigortacı'nın sorumluluğunun devam ettiği süreye karşılık gelen prim, gün esası üzerinden hesap edilerek, fazlası Sigorta Ettiren'in yasal vârislerine iade edilir. Sigortalı'nın bir hastalık veya kaza sonucu tedavi görürken vefat etmesi durumunda tedavi süresi içinde oluşan giderler, poliçe özel ve genel şartları ile sözleşmenin teminat kapsamı dahilince kanuni vârislerine ödenir; poliçede vefat eden Sigortalı'nın dışında başka birey yoksa poliçe hükümsüz kalır. Birden fazla kişinin sigortalı bulunduğu poliçelerde, sigortalılardan birinin vefatı halinde, vefat eden bireye ait Sigortacı'nın sorumluluğunun devam ettiği süreye karşılık gelen prim, gün esası üzerinden hesap edilerek fazlası Sigorta Ettiren'e iade edilir, poliçe devam eder. Vefat eden Sigortalı'ya ait ödenmemiş sağlık giderleri varsa ödenebilmesi için veraset ve vergiye ilişkin evrakların, Sigortalı'nın kanuni vârisleri tarafından Sigortacı'ya iletilmesi gerekir.

14. KİŞİSEL VERİLERİN İŞLENMESİ, AKTARILMASI VE İLGİLİ KİŞİNİN HAKLARI İLE İLGİLİ BİLGİLENDİRME
Sigortalı/Sigorta Ettiren sıfatı ile düzenlenmesini talep edeceğiniz sağlık sigortası teklifleri ile ilgili olarak risk ölçümü yapılabilmesi, tazminat taleplerinin değerlendirilebilmesi, sigorta sözleşmesinden kaynaklanan hakların kullanılması ve yükümlülüklerin yerine getirilmesi, sigorta işlemleri kapsamındaki planlama ve istatistik çalışmalarının yapılabilmesi ve tarafınıza özel fırsatların geliştirilebilmesi için sağlık verileriniz de dahil olmak üzere kişisel verileriniz işlenecektir. Bu kapsamda gerek ileteceğiniz, gerekse ilgili yasal düzenlemeler çerçevesinde T.C. Başbakanlık Hazine Müsteşarlığı, Sigorta Bilgi ve Gözetim Merkezi (SBGM), Türkiye Sigorta Birliği, Sosyal Güvenlik Kurumu, Sağlık Bakanlığı, tüm sağlık kurum ve kuruluşları, diğer sigorta şirketleri ve kamu kurum ve kuruluşları, özel ve resmi sağlık kurumları, eczaneler, laboratuvarlar, hekim ve diğer ilgili üçüncü kişi/kurumlardan hakkınızda bilgi ve belge temin edilmesi gerekebilecektir. Kişisel verileriniz, ilgili sigorta tekliflerinin/poliçelerinin yürürlük tarihi süresince ve mevzuatta öngörülen saklama süreleri boyunca yazılı veya elektronik ortamda muhafaza edilebilecektir. Irkı, etnik köken, siyasi düşünce, felsefi inanç, din, mezhep veya diğer inançlar, kılık ve kıyafet, dernek, vakıf ya da sendika üyeliği, sağlığı, cinsel hayatı, ceza mahkumiyeti ve güvenlik tedbirleriyle ilgili verileriniz ile biyometrik ve genetik verilerinizin özel nitelikli kişisel veri olduğunu, sağlık verilerinizi de içeren kişisel verilerinizin, sağlık hizmetlerinin finansmanı ve yönetilmesi konusunda görev yapan sigorta şirketlerince açık rıza aranmaksızın işlenebileceğini belirtiriz. Kişisel Verilerin Korunması Kanunu uyarınca, kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse bilgi talep etme, işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, yurt içinde/yurtdışında aktarıldığı üçüncü kişileri bilme, eksik/yanlış işlenmişse düzeltilmesini isteme, kanunda sayılan istisnai haller saklı kalmak üzere kanunun 7. maddesinde öngörülen şartlar çerçevesinde silinmesini/yok edilmesini isteme, aktarıldığı üçüncü kişilere yukarıda sayılan işlemlerin bildirilmesini isteme, münhasıran otomatik sistemler ile analiz edilmesi nedeniyle aleyhinize bir sonucun ortaya çıkmasına itiraz etme, kanuna aykırı olarak işlenmesi sebebiyle zarara uğramanız halinde zararın giderilmesini talep etme haklarına sahip olduğunuzu belirtmek isteriz.

15. YASALARDAKİ DEĞİŞİKLİKLER
Bu sigorta sözleşmesi Türkiye Cumhuriyeti'nin ilgili mevzuatına tabi olacaktır.

16. PARA BİRİMİ
Sigorta şirketine ya da Sigorta Ettiren'e yapılacak tüm ödemelerde Türk lirası kullanılacaktır.

17. EKLER
Anlaşmalı Kuruluşlara www.aksigorta.com.tr adresinden ulaşılabilir.
Acil Hizmet Servisi: Tel: 444 27 27
`.trim();

const SISTEM_TALIMATI = `Sen WE Sigorta'nın WhatsApp asistanısın. Sana verilen "AKSAĞLIK SİGORTASI (ÖZEL SAĞLIK SİGORTASI - ÖSS) ÖZEL ŞARTLARI" belgesine dayanarak, müşterinin Özel Sağlık Sigortası (ÖSS) hakkındaki sorusunu cevaplıyorsun.

KURALLAR:
- SADECE aşağıda verilen belge metnine dayanarak cevap ver. Belgede yer almayan hiçbir bilgiyi UYDURMA.
- Eğer sorunun cevabı belgede YOKSA veya belge yetersizse, başka hiçbir şey yazmadan TAM OLARAK şunu yaz: YANIT_YOK
- Eğer cevap belgede varsa: kısa, net, sıcak bir dille (WhatsApp mesajı gibi, 2-6 cümle) cevap ver. Gerekirse madde madde yazabilirsin ama uzatma.
- Emin olmadığın, belgede açıkça yazmayan bir şeyi asla kendi yorumunla tamamlama - böyle bir durumda YANIT_YOK yaz.
- Türkçe cevap ver.
- Teknik terimleri (muafiyet, teminat, bekleme süresi vb.) gerektiğinde kısaca açıkla.
- Senin (ve bu botun) müşterinin kendi poliçesine/hesabına özel bilgilerine (örn. sigortalılık süresi, ÖBYG hakkı, poliçe durumu, ödemeler) erişimin YOK - bunları "kontrol edelim mi", "bakalım mı", "inceleyelim mi" gibi bir teklif ASLA sunma, bunu yapabilecekmiş gibi davranma. Soru müşterinin kendi hesabına/poliçesine özelse (genel poliçe şartları değil, "benim ÖBYG hakkım ne kadar" gibi kişiye özel bir durum sorusuysa), bunu belgeden cevaplayamayacağını belirtip doğrudan danışmanıyla görüşmesini öner (YANIT_YOK yazarak fallback mesajının devreye girmesini sağlayabilirsin).`;

// Musterinin sorusunu, belgeye dayanarak cevaplar. Belgede cevap yoksa ya da
// API kullanilamiyorsa (ANTHROPIC_API_KEY tanimli degil, API hata donuyor vb.)
// standart "danismaninizla gorusun" fallback mesajini dondurur - boylece
// musteri hicbir zaman cevapsiz/hata mesajiyla kalmaz.
const DANISMAN_YONLENDIRME_MESAJI =
  "Bu konudaki detayı elimdeki bilgilerle net olarak cevaplayamıyorum 🙏 Bu konuyla ilgili danışmanınızla görüşmenizi öneririz, size en doğru bilgiyi onlar verecektir.";

async function soruyaCevapVer(soru) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error("ÖSS soru-cevap: ANTHROPIC_API_KEY tanımlı değil - fallback mesajı dönülüyor.");
    return DANISMAN_YONLENDIRME_MESAJI;
  }

  const prompt =
    `${SISTEM_TALIMATI}\n\n--- BELGE BAŞLANGICI ---\n${OZEL_SART_METNI}\n--- BELGE SONU ---\n\n` +
    `Müşterinin sorusu: "${soru}"\n\nCevabın:`;

  try {
    const cevap = await mesajGonder(apiKey, prompt, { maxTokens: 600 });
    const temiz = (cevap || "").trim();
    if (!temiz || temiz === "YANIT_YOK" || temiz.startsWith("YANIT_YOK")) {
      return DANISMAN_YONLENDIRME_MESAJI;
    }
    return temiz;
  } catch (err) {
    console.error("ÖSS soru-cevap API hatası:", err.message);
    return DANISMAN_YONLENDIRME_MESAJI;
  }
}

module.exports = { soruyaCevapVer, DANISMAN_YONLENDIRME_MESAJI };
